name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  check_format:
    runs-on: ubuntu-latest
    name: Check format
    container:
      image: elixir:1.9-slim
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Check format
        run: mix format --check-formatted

  tests:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        include:
          - otp: 21.x
            elixir: 1.11.x
          - otp: 22.x
            elixir: 1.11.x
          - otp: 23.x
            elixir: 1.11.x
          - otp: 21.x
            elixir: 1.10.x
          - otp: 22.x
            elixir: 1.10.x
          - otp: 20.x
            elixir: 1.9.x
          - otp: 21.x
            elixir: 1.9.x
          - otp: 22.x
            elixir: 1.9.x
          - otp: 20.x
            elixir: 1.8.x
          - otp: 21.x
            elixir: 1.8.x
          - otp: 22.x
            elixir: 1.8.x
    needs: check_format
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-elixir@v1.2.0
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: mix test
